# Generated by Django 3.0.2 on 2020-01-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='myuser',
        ),
    ]
