# Generated by Django 3.0.2 on 2020-02-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200202_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_count',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
