# Generated by Django 3.0.2 on 2020-02-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_readrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadRecord',
        ),
    ]
