# Generated by Django 3.0.2 on 2020-02-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200204_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentrecord',
            options={'ordering': ['comment_time']},
        ),
    ]
